/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef __MONOTHEK_CCLOSURE_MARSHAL_MARSHAL_H__
#define __MONOTHEK_CCLOSURE_MARSHAL_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* VOID:ULONG,ULONG (monothek/object/monothek_marshallers.list:1) */
extern
void monothek_cclosure_marshal_VOID__ULONG_ULONG (GClosure     *closure,
                                                  GValue       *return_value,
                                                  guint         n_param_values,
                                                  const GValue *param_values,
                                                  gpointer      invocation_hint,
                                                  gpointer      marshal_data);


G_END_DECLS

#endif /* __MONOTHEK_CCLOSURE_MARSHAL_MARSHAL_H__ */
